---
- name: Copy files from Control Node to Other Nodes
  hosts: all
  tasks:
       - name: Copy lvm script file from /files to OSD Nodes
         copy:
              src: files/lvm_process.sh
              dest: /home/mk2cephtestRHCS_OnM_Scripts/
              mode: 0645
              owner: root
              group: root
          
