---
- name: Format disks on OSDS
  hosts: all
  gather_facts: false
  tasks:
        - name: Wipe disks
          shell: for disk in sd{a..c} sd{g..l}; do wipefs -a /dev/${disk}; done

        - name: create vggroups rocksdb
          shell: vgcreate wal-vg1 /dev/sdf && vgcreate db-vg1 /dev/sd{d..e}

        - name: create volume groups for data on each sata disk
          shell: for disk in sd{a..c} sd{g..l}; do vgcreate data-vg-${disk} /dev/${disk}; done

        - name: create the lvms of the  db 
          shell: for disk in sd{a..c} sd{g..l}; do lvcreate -y -n db-lv-${disk} -L 64G db-vg1; done

        - name: create the lvms of the wal devices
          shell: for disk in sd{a..c} sd{g..l}; do lvcreate -y -n wal-lv-${disk} -l 5260 wal-vg1; done

        - name: create the data logical volumes for the SATA disks
          shell: for disk in sd{a..c} sd{g..l}; do lvcreate -y -n data-lv-${disk} -l 100%FREE data-vg-${disk}; done

          
