---
- name: Register and subscribe RHEL systems
  hosts: all
  tasks:
        - name: Unregister system
          redhat_subscription:
                   state: absent

        - name: register and subscribe systems
          redhat_subscription:
                   username: senestian
                   password: Thierry@1108
                   auto_attach: true
                   release: '8.4'
                   state: present
