--- 
- name: Test Play
  hosts: all
  gather_facts: false
  tasks:
       - name: Test Play
         shell: echo "Helo World"
         register: output
     
       - name: Display output
         debug:
            var: output
