---
- name: Gather Facts
  hosts: all
  become: true
  gather_facts: false
  tasks:
       - name: Display Uptime
         shell: uptime 
         register: output
    
       - name: Display uptime
         debug: 
             var: output.stdout
             
