---
- name: Gather Facts
  hosts: all
  become: true
  gather_facts: true
  tasks:
       - name: Display RedHat Version
         debug: 
             var: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
