---
- name: Enable Ceph Repositories
  hosts: all
  tasks:
       - name: Add RHCS 4.2 Repositories
         rhsm_repository:
               name:
                   - ansible-2-for-rhel-8-x86_64-rpms
                   - rhceph-4-tools-for-rhel-8-x86_64-rpms
               state: enabled
 
      
