---
- name: Enable Ceph Repositories
  hosts: all
  tasks:
       - name: Add RHCS 5 Repositories
         rhsm_repository:
               name:
                   - rhceph-5-tools-for-rhel-8-x86_64-rpms
               state: enabled
 
      
